name: Integration Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Run integration test
        working-directory: integration
        run: go test -run ^TestCTIntegration$ -v
